In [1]:
import os 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import tensorflow as tf
tf.__version__

'2.9.2'

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, GRU, LSTM, Dense

# 2. Keras로 LSTM 구현하기

https://keras.io/api/layers/recurrent_layers/lstm/

사실 실제로 SimpleRNN이 사용되는 경우는 거의 없습니다. 이보다는 LSTM이나 GRU을 주로 사용하는데, 이번에는 임의의 입력에 대해서 LSTM을 사용할 경우를 보겠습니다.

In [4]:
John = [1,0,0,0]
loves = [0,1,0,0]
Jane = [0,0,1,0]
Alex = [0,0,0,1]

train_X = np.array([
    [ John, loves, Jane ],
    [ Jane, loves, Alex ]
]).astype(np.float32)

S = [0] # subject
V = [1] # verb
O = [2] # object

idx2tag = ['S', 'V', 'O']

train_Y = np.array([[S, V, O], [S, V, O]]).astype(np.float32)

print("train_y", train_Y)
print("train_X의 shape", train_X.shape)
print("train_Y의 shape", train_Y.shape)

train_y [[[0.]
  [1.]
  [2.]]

 [[0.]
  [1.]
  [2.]]]
train_X의 shape (2, 3, 4)
train_Y의 shape (2, 3, 1)


In [5]:
num_classes = 3
input_dim = 4  
sequence_length = 3
learning_rate = 0.1


lstm = LSTM(num_classes)
output = lstm(train_X)

print('hidden state : {}, shape: {}'.format(output, output.shape))

hidden state : [[-0.09985117  0.05485465 -0.20872062]
 [-0.11973181  0.00479792 -0.1604197 ]], shape: (2, 3)


In [6]:
# return_sequences = True 
    # many to one - False / many to many - True

lstm = LSTM(3, return_sequences=True, return_state=True)
whole_seq_output, final_memory_state, final_carry_state = lstm(train_X)

print('whole_seq_output: {}, shape: {}'.format(whole_seq_output, whole_seq_output.shape))
print('final_memory_state : {}, shape: {}'.format(final_memory_state, final_memory_state.shape))
print('final_carry_state : {}, shape: {}'.format(final_carry_state, final_carry_state.shape))

whole_seq_output: [[[-0.06298827  0.02220115 -0.04308451]
  [-0.20612237 -0.04158368 -0.14387678]
  [-0.18484746  0.02523317 -0.13857897]]

 [[-0.05228832  0.05618019 -0.01837007]
  [-0.19419679 -0.03087777 -0.13497694]
  [-0.02198333 -0.01652196 -0.19134323]]], shape: (2, 3, 3)
final_memory_state : [[-0.18484746  0.02523317 -0.13857897]
 [-0.02198333 -0.01652196 -0.19134323]], shape: (2, 3)
final_carry_state : [[-0.34696177  0.04639182 -0.35474384]
 [-0.04689917 -0.04913583 -0.3364432 ]], shape: (2, 3)


In [15]:
from tensorflow.keras import layers, models

model = models.Sequential() #모델 호출
model.add(
    layers.LSTM(units=3,
                input_shape = (3, 4), 
                return_sequences = True,
                name='LSTM-1'))

model.add(
    layers.Dense(
        units=3, 
        activation='softmax', 
        name='hidden-to-output')) # 출력을 위한 FFN


model.compile(
    loss='sparse_categorical_crossentropy', 
    optimizer='adam',
    metrics=['accuracy'])


In [10]:
model.fit(train_X, train_Y, epochs= 100)

Epoch 1/100
1/1 [==============================] - 2s 2s/step - loss: 1.0775 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 12ms/step - loss: 1.0770 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 19ms/step - loss: 1.0765 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 9ms/step - loss: 1.0761 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 11ms/step - loss: 1.0756 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 8ms/step - loss: 1.0751 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 8ms/step - loss: 1.0746 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 15ms/step - loss: 1.0742 - accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 10ms/step - loss: 1.0737 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 11ms/step - loss: 1.0732 - accuracy: 0.5000
Epoch 11/100
1/1 [======

In [12]:
lstm(train_X)

[<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
 array([[[-0.06298827,  0.02220115, -0.04308451],
         [-0.20612237, -0.04158368, -0.14387678],
         [-0.18484746,  0.02523317, -0.13857897]],
 
        [[-0.05228832,  0.05618019, -0.01837007],
         [-0.19419679, -0.03087777, -0.13497694],
         [-0.02198333, -0.01652196, -0.19134323]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.18484746,  0.02523317, -0.13857897],
        [-0.02198333, -0.01652196, -0.19134323]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.34696177,  0.04639182, -0.35474384],
        [-0.04689917, -0.04913583, -0.3364432 ]], dtype=float32)>]

In [17]:
lstm2 = layers.LSTM(3, return_state = True, return_sequences=True)
lstm2(train_X)
# return_sequences, return_state가 True냐 False냐에 따라 최종 출력값이 달라짐
    # return_sequences : True(many to many 등) // False(many to one 등)
    # return_state : last state in addiction to the output

[<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
 array([[[-0.00506702, -0.04359004,  0.10605907],
         [ 0.02078469, -0.15217848,  0.0077216 ],
         [ 0.14552084, -0.23856458, -0.1211035 ]],
 
        [[ 0.13402778, -0.07307423, -0.11704355],
         [ 0.06166756, -0.15819265, -0.11065076],
         [ 0.09865902, -0.0478793 , -0.01339513]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 0.14552084, -0.23856458, -0.1211035 ],
        [ 0.09865902, -0.0478793 , -0.01339513]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 0.251247  , -0.40556067, -0.24083446],
        [ 0.24405944, -0.09331451, -0.02428293]], dtype=float32)>]

https://www.tensorflow.org/api_docs/python/tf/keras/layers/LSTM

In [ ]:
predictions = model.predict(train_X)
for i, prediction in enumerate(predictions):
  print(prediction)
  print(np.argmax(prediction, axis=1))
  result_str = [idx2tag[c] for c in np.argmax(prediction, axis=1) ]
  print("\tPrediction str: ", "".join(result_str))


[[0.8940147  0.03449708 0.07148813]
 [0.04685312 0.9033953  0.04975158]
 [0.11443406 0.04352104 0.8420449 ]]
[0 1 2]
	Prediction str:  SVO
[[0.8195169  0.04282429 0.13765882]
 [0.03784835 0.90291107 0.05924062]
 [0.07242088 0.04501116 0.88256794]]
[0 1 2]
	Prediction str:  SVO


모델을 이해하려면 weight 개수(W0\~Wn)를 세어봐야 합니다.

In [11]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 LSTM-1 (LSTM)               (None, 3, 3)              96        
                                                                 
 hidden-to-output (Dense)    (None, 3, 3)              12        
                                                                 
Total params: 108
Trainable params: 108
Non-trainable params: 0
_________________________________________________________________


In [ ]:
for model_weight in model.weights:
    print(model_weight.name, '=>', model_weight.shape)

### 문제1 

In [ ]:
model = Sequential()
model.add(LSTM(7, input_shape=(100,5)))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_3 (LSTM)               (None, 7)                 364       
                                                                 
Total params: 364
Trainable params: 364
Non-trainable params: 0
_________________________________________________________________


- W_forget : (num_units + input_dim + 1) * num_units
- W_input : (num_units + input_dim + 1) * num_units
- W_output : (num_units + input_dim + 1) * num_units
- W_cell : (num_units + input_dim + 1) * num_units

### 문제2

In [ ]:
model = Sequential()
model.add(LSTM(5, input_shape = (2, 10)))
model.add(Dense(1))
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_4 (LSTM)               (None, 5)                 320       
                                                                 
 dense_2 (Dense)             (None, 1)                 6         
                                                                 
Total params: 326
Trainable params: 326
Non-trainable params: 0
_________________________________________________________________


- W_forget : (num_units + input_dim + 1) * num_units
- W_input : (num_units + input_dim + 1) * num_units
- W_output : (num_units + input_dim + 1) * num_units
- W_cell : (num_units + input_dim + 1) * num_units

In [ ]:
# weight 개수 카운팅

### 문제3

In [ ]:
model = Sequential()
model.add(LSTM(5, input_shape = (2, 10), return_sequences=True))
model.add(LSTM(7))
model.add(Dense(1))
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_5 (LSTM)               (None, 2, 5)              320       
                                                                 
 lstm_6 (LSTM)               (None, 7)                 364       
                                                                 
 dense_3 (Dense)             (None, 1)                 8         
                                                                 
Total params: 692
Trainable params: 692
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 첫번째 레이어의 파라미터 개수

320

In [ ]:
# 두번째 레이어의 파라미터 개수 


364

In [ ]:
# 세번째 레이어의 파라미터 개수 

8

# 3. Keras로 GRU 구현하기

https://keras.io/api/layers/recurrent_layers/gru/

In [ ]:
gru = GRU(num_classes)
output = gru(train_X)

print('hidden state : {}, shape: {}'.format(output, output.shape))

hidden state : [[-0.3331254   0.15914953 -0.20464015]
 [-0.226817    0.35800463 -0.16532332]], shape: (2, 3)


In [ ]:
# return_sequences = True 
gru = GRU(3, return_sequences=True, return_state=True)
whole_sequence_output, final_state= gru(train_X)

print('whole_seq_output: {}, shape: {}'.format(whole_seq_output, whole_seq_output.shape))
print('final_state : {}, shape: {}'.format(final_state, final_state.shape))

whole_seq_output: [[[-0.09133016 -0.02071412  0.14170164]
  [ 0.02361282  0.06159054  0.03471249]
  [ 0.06012786 -0.04471743 -0.08892121]]

 [[ 0.03587217 -0.0941782  -0.11587585]
  [ 0.08149255  0.02020295 -0.18497597]
  [ 0.03355836 -0.02213107 -0.14921774]]], shape: (2, 3, 3)
final_state : [[ 0.10870809  0.3283546  -0.2419539 ]
 [-0.13706805 -0.10124536 -0.31973392]], shape: (2, 3)


In [ ]:
from tensorflow.keras import layers, models

model = models.Sequential() #모델 호출
model.add(
    layers.GRU(
        units=,
        input_shape =  
        return_sequences = , 
        reset_after=False, 
        name='GRU-1')) # RNN 호출

# reset_after : keras 구현을 하면서 병렬처리를 위해 공식을 수정(bias를 2개로 나눔)하였는데, 원래 논문에 나온 공식으로 계산하기 위해 False로 수정

model.add(
    layers.Dense(
        units=, 
        activation=, 
        name='hidden-to-output')) # 출력을 위한 FFN


model.compile(
    loss='sparse_categorical_crossentropy', 
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
    metrics=['accuracy'])


In [ ]:
model.fit(train_X, train_Y, epochs= 100)

Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 1.1492 - accuracy: 0.1667
Epoch 2/100
1/1 [==============================] - 0s 8ms/step - loss: 1.1400 - accuracy: 0.1667
Epoch 3/100
1/1 [==============================] - 0s 8ms/step - loss: 1.1317 - accuracy: 0.0000e+00
Epoch 4/100
1/1 [==============================] - 0s 8ms/step - loss: 1.1240 - accuracy: 0.0000e+00
Epoch 5/100
1/1 [==============================] - 0s 9ms/step - loss: 1.1170 - accuracy: 0.0000e+00
Epoch 6/100
1/1 [==============================] - 0s 8ms/step - loss: 1.1105 - accuracy: 0.1667
Epoch 7/100
1/1 [==============================] - 0s 11ms/step - loss: 1.1044 - accuracy: 0.1667
Epoch 8/100
1/1 [==============================] - 0s 13ms/step - loss: 1.0985 - accuracy: 0.3333
Epoch 9/100
1/1 [==============================] - 0s 15ms/step - loss: 1.0929 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 10ms/step - loss: 1.0874 - accuracy: 0.6667
Epoch 11/100
1

In [ ]:
predictions = model.predict(train_X)
for i, prediction in enumerate(predictions):
  print(prediction)
  print(np.argmax(prediction, axis=1))
  result_str = [idx2tag[c] for c in np.argmax(prediction, axis=1) ]
  print("\tPrediction str: ", "".join(result_str))


[[0.8838949  0.03892433 0.07718088]
 [0.03276091 0.89175344 0.07548558]
 [0.12529185 0.05806499 0.8166431 ]]
[0 1 2]
	Prediction str:  SVO
[[0.8183433  0.04454137 0.13711534]
 [0.03734664 0.8973856  0.06526773]
 [0.07024387 0.06087027 0.8688859 ]]
[0 1 2]
	Prediction str:  SVO


모델을 이해하려면 weight 개수(W0\~Wn)를 세어봐야 합니다.

In [ ]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 GRU-1 (GRU)                 (None, 3, 3)              72        
                                                                 
 hidden-to-output (Dense)    (None, 3, 3)              12        
                                                                 
Total params: 84
Trainable params: 84
Non-trainable params: 0
_________________________________________________________________


In [ ]:
for model_weight in model.weights:
    print(model_weight.name, '=>', model_weight.shape)

### 문제1

In [ ]:
model = Sequential()
model.add(GRU(9, input_dim = 10, return_sequences=True, reset_after=False))
# reset_after : keras 구현을 하면서 병렬처리를 위해 공식을 수정(bias를 2개로 나눔)하였는데, 원래 논문에 나온 공식으로 계산하기 위해 False로 수정
model.add(GRU(6, reset_after = False))
model.add(Dense(3))
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru_6 (GRU)                 (None, None, 9)           540       
                                                                 
 gru_7 (GRU)                 (None, 6)                 288       
                                                                 
 dense_6 (Dense)             (None, 3)                 21        
                                                                 
Total params: 849
Trainable params: 849
Non-trainable params: 0
_________________________________________________________________


- W_reset : (num_units + input_dim + 1) * num_units
- W_update : (num_units + input_dim + 1) * num_units
- W_new : (num_units + input_dim + 1) * num_units


In [ ]:
# 첫번째 레이어의 파리미터 개수

540

In [ ]:
# 두번째 레이어의 파라미터 개수

288

In [ ]:
# 세번째 레이어의 파리미터 개수

21

### reference

- https://github.com/ukairia777/tensorflow-nlp-tutorial/blob/main/08.%20RNN/8-4.%20understanding_simplernn_and_lstm.ipynb